version: "3.8"
services:
  ros:
    build: .
    image: rosbags_extractor
    command: /bin/bash
    stdin_open: true
    tty: true

    volumes:
      - ".:/RosbagsExtractor"
      - "~/datasets/ros_dataset:/RosbagsExtractor/ros_datasets"

    # Network
    # privileged: true
    # network_mode: host
    # cap_add:
    #   - NET_ADMIN
    # devices:
    #   - "/dev/net/tun:/dev/net/tun"
    # ports:
    #   - "1195:1194/udp"

    # For Display
    # environment:
    #   - DISPLAY=${DISPLAY}
    # volumes:
    #   - type: bind
    #     source: /tmp/.X11-unix
    #     target: /tmp/.X11-unix